server:
  port: 8180


#token加密
jwt:
  pri-key: MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEAteeZx56BWM5qH7RShXsq1u6IhOWF+DJ5CPUSCArzT6MHSOoNOY0HaW+XMh4NgjHVp5oI/R/m5MChk3al0yGl8wIDAQABAkEAjR63C8lpOZcxd5UybAGos4Psf4V9EJc/lPZjXb/5EO7tTUPg674LLFwDxnoOsbKSRG4UTBGgMr4GVpcN8vIKoQIhAPJ7vR6FXE4shp4wUied804Xik54rLzR6BB1TLSL7d4jAiEAwAtmAm2kw1tBdYCsBmEbyuHTJw73UH/s6IYyf9zBTfECIQDAI2B1wMKlhw6cZjmS/st+A5UqHODzNXinIetH3OD89QIgZHjSKq0QSUCB86aY2VGOx8rzvHiA/TWgTVqAKxLkcxECIQCEgo3hq28oQIntxkJnbemvmOfhzfQvMlT25YM9ldxLmQ==
  pub-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALXnmceegVjOah+0UoV7KtbuiITlhfgyeQj1EggK80+jB0jqDTmNB2lvlzIeDYIx1aeaCP0f5uTAoZN2pdMhpfMCAwEAAQ==

#http连接池
http-pool:
  max-total: 200
  default-max-per-route: 100
  connect-timeout: 5000
  connection-request-timeout: 1000
  socket-timeout: 65000
  validate-after-inactivity: 2000

#oa配置
oa:
  app-interface-url: http://localhost:8080/fzoa/appinterface.action
  app-operation-url: http://localhost:8080/fzoa/appOperation.action

logging:
  config: classpath:log4j2.xml
